;;; company-distel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-distel.el

(autoload 'company-distel "company-distel" "\
Erlang/Distel completion backend for Company-mode.

(fn COMMAND &optional ARGS &rest IGNORE)")
(register-definition-prefixes "company-distel" '("company-distel-"))

;;; End of scraped data

(provide 'company-distel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-distel-autoloads.el ends here
